"""create threat table

Revision ID: db641254a248
Revises: 67b8cb0f8857
Create Date: 2022-07-17 11:21:42.277389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db641254a248'
down_revision = '67b8cb0f8857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('threat_id_info', sa.String(length=16), nullable=False),
    sa.Column('domain_count', sa.Integer(), nullable=False),
    sa.Column('tag_count', sa.Integer(), nullable=False),
    sa.Column('itel_count', sa.Integer(), nullable=False),
    sa.Column('judge', sa.Integer(), nullable=False),
    sa.Column('poc', sa.Boolean(), nullable=False),
    sa.Column('ctime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', name='threat_table_ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat')
    # ### end Alembic commands ###
